name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build ðŸ› ï¸
    uses: ./.github/workflows/run_build.yml

  release:
    needs:
      - build
    name: Create Release ðŸ“¢
    runs-on: ubuntu-24.04
    steps:
      - name: Download x86_64 Tarball ðŸ“¥
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: tarball-x86_64

      - name: Download aarch64 Tarball ðŸ“¥
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: tarball-aarch64

      - name: Generate Checksums ðŸ”‘
        run: |
          sha256sum nixos.wsl > nixos.wsl.sha256
          sha256sum nixos.aarch64.wsl > nixos.aarch64.wsl.sha256

      - name: Attach to Release ðŸ“Ž
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          files: |
            nixos.wsl
            nixos.wsl.sha256
            nixos.aarch64.wsl
            nixos.aarch64.wsl.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
