name: Build Tarball

on:
  workflow_call: {}

jobs:
  tar:
    name: Tarball (${{ matrix.system }}) üõ†Ô∏è
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            system: x86_64
            config: default
            filename: nixos.wsl
          - runner: ubuntu-24.04-arm
            system: aarch64
            config: aarch64
            filename: nixos.aarch64.wsl
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install Nix ‚ùÑÔ∏è
        uses: ./.github/actions/install-nix

      - name: Set Version üè∑Ô∏è
        uses: ./.github/actions/version
        id: version

      - name: Summary Headline üìù
        run: echo '## NixOS-WSL ${{ steps.version.outputs.version }}' >> $GITHUB_STEP_SUMMARY

      - name: Build Tarball üõ†Ô∏è
        uses: ./.github/actions/build-wsl-tarball
        with:
          config: ${{ matrix.config }}
          filename: ${{ matrix.filename }}

      - name: Upload Tarball üì§
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: tarball-${{ matrix.system }}
          path: ${{ matrix.filename }}
